% Generated by MATLAB(R) 9.12 (R2022a) and WLAN Toolbox 3.4 (R2022a).
% Generated on: 03-Nov-2022 11:09:51

%This is the code for dataset 1_0 (due 01/18 for DSTL). No noise, channel
%model, just vanilla signal. 2k samples for each. Run from
%/home/genesys/Downloads/Stratis_Kaushik_Proposal/dataset1_0' directory 

trainDir = fullfile('/media/genesys/Seagate Portable Drive/test_data_1_1/802_11b_upsampled');
frameNo = 1;
row_count = 1;
SR_Radio = 20e6;
bandwidth = 11e6;
sr_signal = bandwidth;
% frameDuration = length(waveform)/Fs;
%% Generating 802.11b/g (DSSS) waveform
% 802.11b/g (DSSS) configuration
for frameNo = 1:250 % first 1000 is 1/2 rate , 2nd 1000 is 3/4 rate

    dsssCfg = wlanNonHTConfig('Modulation', 'DSSS', ...
        'DataRate', '5.5Mbps', ...
        'Preamble', 'Long', ...
        'LockedClocks', true, ...
        'PSDULength', 1000);
    
    numPackets = 1;
    % input bit source:
    in = randi([0, 1], 1000, 1);
    
    
    % Generation
    waveform = wlanWaveformGenerator(in, dsssCfg, ...
        'NumPackets', 1, ...
        'IdleTime', 0);
    
    Fs = wlanSampleRate(dsssCfg); 								 % Specify the sample rate of the waveform in Hz

    %RESAMPLING/UPSAMPLING TO 20MHz
     [Num Den] = rat(SR_Radio/sr_signal);
     rxWaveBaseline_resampled = resample(waveform,Num,Den);
    
    %% Visualize
    % Time Scope
%     timeScope = timescope('SampleRate', Fs, ...
%         'TimeSpanOverrunAction', 'scroll', ...
%         'TimeSpanSource', 'property', ...
%         'TimeSpan', 2.7273e-06);
%     timeScope(waveform);
%     release(timeScope);
%     
%     % Spectrum Analyzer
%     spectrum = dsp.SpectrumAnalyzer('SampleRate', SR_Radio); %want to plot upsampled with new sampling rate
%     spectrum(rxWaveBaseline_resampled);
%     release(spectrum);
%     
    % Save IQ
    label = '802.11b_IQ';
    fname3 = fullfile(trainDir, [label '_frame_' strrep(num2str(frameNo),' ','')]);
    % write_binary (fname, 2, waveform)
    save(fname3 + ".mat", 'waveform')
    
    fileID = fopen(fname3 + ".yaml",'w');
        metadata = strcat('# ---------------------------------------------------------------------,\n', ...
            '# Waveform Configuration]\n', ...
            '# ---------------------------------------------------------------------,]\n', ...
            'standard: "802.11b_matlab"\n', ...
            'modulation: "DSSS"\n', ... 
            'bandwidth: ' + " " ,num2str(SR_Radio), '\n', ...
            'sampling_rate: ' + " " ,num2str(SR_Radio), '\n', ...
            'PSDU_length_bytes: 1000');   
    %             'time_duration: ' + " ", num2str(frameDuration), '\n', ... %is this needed ?
    
            
        fprintf(fileID, metadata);
        fclose(fileID);
end


for frameNo = 251:500 % first 1000 is 1/2 rate , 2nd 1000 is 3/4 rate

    dsssCfg = wlanNonHTConfig('Modulation', 'DSSS', ...
        'DataRate', '5.5Mbps', ...
        'Preamble', 'Long', ...
        'LockedClocks', true, ...
        'PSDULength', 1000);
    
    numPackets = 1;
    % input bit source:
    in = randi([0, 1], 1000, 1);
    
    
    % Generation
    waveform = wlanWaveformGenerator(in, dsssCfg, ...
        'NumPackets', 1, ...
        'IdleTime', 0);
    
    Fs = wlanSampleRate(dsssCfg); 								 % Specify the sample rate of the waveform in Hz
    
    %% Visualize
    % Time Scope
%     timeScope = timescope('SampleRate', Fs, ...
%         'TimeSpanOverrunAction', 'scroll', ...
%         'TimeSpanSource', 'property', ...
%         'TimeSpan', 2.7273e-06);
%     timeScope(waveform);
%     release(timeScope);
%     
%     % Spectrum Analyzer
%     spectrum = dsp.SpectrumAnalyzer('SampleRate', Fs);
%     spectrum(waveform);
%     release(spectrum);
    
    % Save IQ
    label = '802.11b_IQ';
    fname3 = fullfile(trainDir, [label '_frame_' strrep(num2str(frameNo),' ','')]);
    % write_binary (fname, 2, waveform)
    save(fname3 + ".mat", 'waveform')
    
    fileID = fopen(fname3 + ".yaml",'w');
        metadata = strcat('# ---------------------------------------------------------------------,\n', ...
            '# Waveform Configuration]\n', ...
            '# ---------------------------------------------------------------------,]\n', ...
            'standard: "802.11b_matlab"\n', ...
            'modulation: "DSSS"\n', ... 
            'bandwidth: ' + " " ,num2str(Fs), '\n', ...
            'sampling_rate: ' + " " ,num2str(Fs), '\n', ...
            'PSDU_length_bytes: 1000');   
    %             'time_duration: ' + " ", num2str(frameDuration), '\n', ... %is this needed ?
    
            
        fprintf(fileID, metadata);
        fclose(fileID);
end





